### ISSUE TITLE
Updating accordion item height after content slot load

### ISSUE THREAD

**Issue by Chris-Pratt-Clystnet** [vanderb/vue-badger-accordion#10]
So in this use case I am loading items into the content of an accordion item via a server request.

Now my issue is if the user opens the accordion before the content has loaded then when the content loads the height of the accordion item does not update till I close and re-open the accordion item.

So does anyone know what the best way to get the accordion to update its height after the content load has happened.

**Comment by vanderb** [comment]
Hi @Chris-Pratt-Clystnet. Thanks for this report. There is a method called "calculateAllPanelsHeight". Maybe this could be called after items loaded?

Or am I misunderstood something?

**Comment by Chris-Pratt-Clystnet** [comment]
@vanderb Yes i thought that might be one way as each accordion item has a component in it so I guess i could get the components to emit when they have loaded and then run that function.

Just wondering about this as it seems if the content of the accordion item changes then shoudnt the accordion item automatically re-adjust its self. Not a problem if not as I will just go with the first option.
