### ISSUE TITLE
Is it compatible with nuxt?

### ISSUE THREAD

**Issue by khataev** [vanderb/vue-badger-accordion#16]
Could not manage to use in nuxt project, I'm getting this error

```
in ./node_modules/vue-badger-accordion/src/BadgerAccordionItem.vue
Module not found: Error: Can't resolve 'sass-loader' in '/Users/khataev/Documents/personal-code/nodejs/izi-ndfl-front'
```

I have plugins/accordion.js

```
import Vue from 'vue'
import { BadgerAccordion, BadgerAccordionItem } from 'vue-badger-accordion'
Vue.component('BadgerAccordion', BadgerAccordion)
Vue.component('BadgerAccordionItem', BadgerAccordionItem)
```

nuxt.config.js

```
  plugins: [
    { src: '~/plugins/accordion', ssr: false },
  ],
```

This [issue](https://github.com/vuejs-templates/webpack/issues/121) suggest to install

```
npm install --save-dev node-sass sass-loader
```

But it leads to the following error

```
You are using the runtime-only build of Vue where the template compiler is not available. Either pre-compile the templates into render functions, or use the compiler-included build.
```

**Comment by vanderb** [comment]
Hi @khataev ,
the implementation-part above seems correct. 

Dont think the error belongs to this package, but with the implementation of vue itself.

You can try to implement the dist version of vue:

`import Vue from 'vue/dist/vue.js';`

**Comment by benwalsh** [comment]
I get the error `Cannot use import statement outside a module` when trying to use with nuxt.

**Comment by ivanopol** [comment]
Same problem: Cannot use import statement outside a module

**Comment by vanderb** [comment]
Hi guys,
Sorry to let you hanging out so long.

I've started to rebuild and clean up the build-process for this package.

Just released Version 2 of this package, now you can implement it also in Nuxt.

**Update to v2:** 
Change version in package.json to 2.0.2
`"vue-badger-accordion": "^2.0.2"`

**Implementing components to nuxt**
Create a new nuxt-plugin `plugins/vue-badger-accordion.js`

```javascript
import Vue from 'vue'

import {BadgerAccordion, BadgerAccordionItem} from 'vue-badger-accordion'
Vue.component('BadgerAccordion', BadgerAccordion);
Vue.component('BadgerAccordionItem', BadgerAccordionItem);
```

Add plugin to plugins-section nuxt.config.js
```javascript
plugins: [
  {src: '~/plugins/vue-badger-accordion.js', ssr: false}
],
```

Please let me know, if that fixed it.

**Comment by luksak** [comment]
@vanderb  Thanks, that fixes the issue!

**Comment by vanderb** [comment]
Great, think I can close that issue. If you found anything else let me know.

**Comment by Peto** [comment]
Hi, I am using SSR with nuxt 2 and I am getting this warning after npm run dev.
`The client-side rendered virtual DOM tree is not matching server-rendered content. This is likely caused by incorrect HTML markup, for example nesting block-level elements inside <p>, or missing <tbody>. Bailing hydration and performing full client-side render.`
But badger-accordion is at least showing and functioning. When I use <client-only> it works. But I need it for SSR, so I can't use this.

After building the app, the badger-accordion is not showing. 
Thank you.
