### ISSUE TITLE
Throws 'document not defined' while using with nuxt.

### ISSUE THREAD

**Issue by thevipinmishra** [vanderb/vue-badger-accordion#19]
After installing it and using it, I got an error called 'Cannot use import statement outside a module'.

Then I came across this issue on official nuxt.js documentation ( [here ](https://nuxtjs.org/docs/2.x/directory-structure/plugins/)) and I did what they suggested to fix this, but now, I'm getting this error and I have no idea how to fix it.

This is what I get now

![image](https://user-images.githubusercontent.com/52159805/107839749-0f2c7c00-6dd4-11eb-9568-74b92d341428.png)

**Comment by vanderb** [comment]
There was already a question about nuxt-implementation.
Please take a look at #16.

You can also try to wrap your component in client-tags


```
<client-only>
<badger-accordion>
    <badger-accordion-item>
        <template slot="header">First Accordion Header</template>    
        <template slot="content">First Accordion Content</template>  
    </badger-accordion-item>
</badger-accordion>
</client-only>
```

Does that help?
