### ISSUE TITLE
Removing accordion items bug

### ISSUE THREAD

**Issue by Chris-Pratt-Clystnet** [vanderb/vue-badger-accordion#8]
I currentley have each item of the accordcion added via a for loop.

Now when the array for this loop updates because an item has been removed the item does not get removed from the accordion.

I can see that the item no longer exsists in Vue but it is not being removed from the page DOM.

How do I force the page DOM to get updated ?

**Comment by vukasinovic** [comment]
Hello @Chris-Pratt-Clystnet ,
I had the same problem with not updating DOM when removing items from array using v-for.
What I did is after removing element from array I used JQuery to remove badger-accordion-item from DOM. Here is an example function that I used. This is not best solution but it will do the work until this package is updated.
```
removeItem(index) {
    this.listItems.splice(index, 1);  
    $(this.$refs.itemsAccordion.accordion.toggleEl[index]).parent().next().remove();  
    $(this.$refs.itemsAccordion.accordion.toggleEl[index]).parent().remove();  
}
```

also don't forget to put ref attribute to badger-accordion
```
 <badger-accordion ref="itemsAccordion" :options="{...}">
      ...
 </badger-accordion>
```
HTML construction of badger is little bit confusing so this was only solution I could come up for now.
Hope this helps

**Comment by vanderb** [comment]
Hi,
this happens because original badger-accordion sadly is not reactive itself.
Good note. I will work on this, thank you.

**Comment by Chris-Pratt-Clystnet** [comment]
@vukasinovic Thanks for the tip I will give that a go

@vanderb Thanks I will look out for the update with it in :-)

**Comment by vanderb** [comment]
@Chris-Pratt-Clystnet Please update to v 1.1.4. This should be fixed there. The rerender-method should be called automatically, if the slot changed from outside.

Can you verify this? I will then close this issue.

**Comment by Chris-Pratt-Clystnet** [comment]
@vanderb Just tested this and all working fine :-)
